export default Fonts = {
  FONT_FACE_TITLE: '',
  FONT_SIZE_TITLE: 20,
  FONT_FACE_CAPTION:  '',
  FONT_SIZE_CAPTION: 17,
  FONT_FACE_DESCRIPTION:  '',
  FONT_SIZE_DESCRIPTION: 14,
  FONT_FACE_BUTTON: '',
  FONT_SIZE_BUTTON: 16,
  FONT_FACE_BOLD: '',
  FONT_FACE_MEDIUM: '',
  FONT_FACE_REGULAR: '',
};
